@startuml

' hide the spot
' hide circle

' avoid problems with angled crows feet
skinparam linetype ortho

entity "Device" as e01 {
  *id : UUID <<generated>>
  --
  name : text
  type : text
  status : text
  registration_at : Date
}

entity "Room" as e02 {
  *id : UUID <<generated>>
  --
  name : string
  icon_url: string
  description: string
  owner_id: UUID
  house_id: UUID <<FK>>
  created_at : Date
}

entity "House" as e03 {
  *id : UUID <<generated>>
  --
  name : string
  icon_url: string
  description: string
  created_at : Date
}

entity "SensorHistory" as e04 {
  *id : UUID <<generated>>
  --
  device_id : UUID <<FK>>
  type: string
  data: json
  created_at : Date
}

entity "User" as e05 {
  *id : UUID <<generated>>
  name : string
  email : string
  birthdate : Date
  role : String
  String : password
  registrationAt : Date
}

entity "User_to_house" as e06 {
  house_id: UUID
  owner_id: UUID
}

entity "User_to_device" as e07 {
  device_id: UUID
  owner_id: UUID
}

e01 |o..|| e02
e02 }o..|| e03
e01 ||..o{ e04
e05 ||..o{ e01
e05 ||..o{ e06
e03 ||..o{ e06
e05 ||..o{ e07
e01 ||..o{ e07

@enduml